### ISSUE TITLE
Pavics search is broken

### ISSUE THREAD

**Issue by dbyrns** [Ouranosinc/PAVICS-DataCatalog#38]
wps_pavicssearch.py line 193 is mapping the response of catalog.pavicsearch into a tuple but the function pavicssearch is returning a single value.
I propose to replace the line : 
(search_result, search_url) = catalog.pavicsearch(
by :
search_result = catalog.pavicsearch(

search_url doesn't seem to be used anyway...

**Comment by bstdenis** [comment]
I modified pyPavics (0.4.2), this is now the correct way to call the function, did you rebuild everything?

https://github.com/Ouranosinc/pyPavics/blob/0.4.2/pavics/catalog.py

**Comment by dbyrns** [comment]
I will update my PR by updating the pyPavics version and removing the quick fix

**Comment by dbyrns** [comment]
Ok the PR is updated... could you review it please?

**Comment by bstdenis** [comment]
Those changes are already in master, the PR has conflicts. I think you are behind in your branch.

**Comment by dbyrns** [comment]
Ok my bad, so the issue was with the 0.6.1 version. But it is fixed with the 0.6.3. I will remove my PR.
But I do not understand why the catalog return no results... Still investigating on that.

**Comment by bstdenis** [comment]
There's a bug in the solr request, trying to track it down...

**Comment by bstdenis** [comment]
The bug I ran into was that some NetCDF global attributes has trailing white spaces, I will add a .strip() call in those in the crawler.

Can you give me the search you were trying to do to check on my end?

**Comment by dbyrns** [comment]
As simple as that : https://hirondelle.crim.ca/twitcher/ows/proxy/catalog/pywps?service=WPS&request=execute&version=1.0.0&identifier=pavicsearch&storeExecuteResponse=true&status=true&DataInputs=

**Comment by bstdenis** [comment]
If I look at https://hirondelle.crim.ca/wpsoutputs/catalog/063f822e-3356-11e8-b1a5-0242ac12000a/solr_result_2018-03-29T13:35:20Z_.json

```
responseHeader |  
-- | --
status | 0
QTime | 0
params |  
sort | "id asc"
fq | "type:File"
rows | "10"
indent | "true"
q | "*"
start | "0"
wt | "json"
fl | "*,score"
response |  
start | 0
maxScore | 1
numFound | 0
docs | []
```

It's the same request I use when running on my local solr with http://localhost:8009/pywps?service=WPS&request=execute&version=1.0.0&identifier=pavicsearch&DataInputs=

```
responseHeader |  
-- | --
status | 0
QTime | 1
params |  
sort | "id asc"
fq | "type:File"
rows | "10"
indent | "true"
q | "*"
start | "0"
wt | "json"
fl | "*,score"
response |  
start | 0
maxScore | 1
numFound | 1740
```

Is the solr database empty?

**Comment by bstdenis** [comment]
I'm building a 0.6.4 release with at least my trailing white space fix and the proper version in setup.py. I'm out of ideas for what the problem on hirondelle is...

**Comment by dbyrns** [comment]
Is the search working on medus?

**Comment by bstdenis** [comment]
No. ok, the most likely thing is that it's removing all the results through:

```
if not mag.has_view_perm(doc['url']):
    search_result['response']['docs'].pop(i)
```

When we run a local PAVICS-DataCatalog, magpie_host is not active and that whole part is skipped

**Comment by dbyrns** [comment]
I run in debugger with a magpie host set properly and this part is not skipped and the permission allow me to get result.

**Comment by huard** [comment]
David, it's not clear to me what should be done and by whom to fix this. Please advise.

**Comment by huard** [comment]
From @moulab88 : 
```
ConnectionError: HTTPConnectionPool(host='boreas.ouranos.ca', port=8983): Max retries exceeded with url: /solr/birdhouse/select?start=0&amp;rows=1000&amp;q=tasmax_kda_208011_se.nc%20AN

D%20ouranos.climex.QC11d3_CCCma-CanESM2_rcp85.day.historical-r1-r1i1p1.tasmax&amp;fl=*,score&amp;sort=id+asc&amp;wt=json&amp;indent=true (Caused by NewConnectionError('&lt;requests.pac

kages.urllib3.connection.HTTPConnection object at 0x7f4d6f4c6d10&gt;: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by dbyrns** [comment]
@ldperron I heard that you can help us again in Pavics and this issue is really a blocker for us. I can help you to get started quickly.

**Comment by ldperron** [comment]
Fix is here!
https://github.com/Ouranosinc/PAVICS/commit/ae7628638a86aee39596c5dc25f68f5345fb5060
