### ISSUE TITLE
Issues accessing solr

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/PAVICS-DataCatalog#40]
@bstdenis may have gone over this with me, but I'm having issues accessing the solr service when housed on an external server. Launching processes appears to be working, but I see no way of accessing solr using the method provided (http://{server}:{port}/solr.

I have tried with addresses suggest that solr is within twitcher (/twitcher/ows/proxy/solr and others), but that is probably not the correct way. @dbyrns are you familiar with loading the solr service? I simply want to verify that files are at least visible in backend.

**Comment by dbyrns** [comment]
Have you try the url http://{server}:{port}/solr/#/birdhouse/query?
If the {port} is open in the firewall you should be able to see an interface to make solr queries
Also look into the docker-compose.yml to know the good port on which solr has been setup.

**Comment by dbyrns** [comment]
And no solr is not behind twitcher since it should not be available publicly... The DataCatalog is the public interface for solr.
